### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by el-davo** [jpgrusling/node-wmi#2]
Hi

I get this error when trying the first example

TypeError: this.exec is not a function
    at new Query (C:\GIT\ect-client\node_modules\node-wmi\lib\Query.js:369:10)
    at Object.Query (C:\GIT\ect-client\node_modules\node-wmi\lib\Query.js:343:12)
    at Object.<anonymous> (C:\GIT\ect-client\test.js:3:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)

Code is this

```
var wmi = require('node-wmi');

wmi.Query({
  class: 'Win32_BIOS'
}, function(err, bios) {
  console.log(bios);
});

```

**Comment by pagenbag** [comment]
Same problem :-/

**Comment by colefranzcsi** [comment]
So, I looked at the code in Query.js and it looks like there was recently an issue and it's calling exec before it's executed. If you switch line 372 above line 367 it looks like everything works as expected.
