### ISSUE TITLE
Deprecation warning by moment.js

### ISSUE THREAD

**Issue by s-a** [jpgrusling/node-wmi#4]
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 20150304000000.000000+000, _f: undefined, _strict: undefined, _locale: [object Object]

**Comment by Zinglish** [comment]
It's worth noting that to install the patched version by @s-a you must use the command `npm install s-a/node-wmi.git##fix-moment-deprecation-warning` because his fix branch is named `#fix-moment-deprecation-warning` (with a #)...why tho?

Kinda wish the author of `node-wmi` would accept your pull request though.

**Comment by s-a** [comment]
Sorry for the hash. :O) It seems @Zinglish does not watch this repo...

**Comment by Zinglish** [comment]
Lmmfao, that's quite amusing that he doesn't watch his own repo. Maybe he didn't expect it to become somewhat popular...

Anyway, @s-a thanks for the fix :)

**Comment by s-a** [comment]
Maybe he do not want to maintain it anymore. 
Since this issue is open a few month we should think about to make a hard fork together and republish on npm?

**Comment by s-a** [comment]
Thank you!

**Comment by VertigoRay** [comment]
Still getting a deprecation warning by moment.js:

```
> wmi.Query({
...   class: 'Win32_BIOS'
... }, function(err, bios) {
...   console.log(bios);
... });
Query {
  _params:
   { class: 'Win32_BIOS',
     host: 'localhost',
     namespace: 'root\\CIMV2',
     password: undefined,
     props: undefined,
     username: undefined,
     where: undefined } }
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 20140609000000.000000+000, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:320:94)
    at configFromString (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:2178:11)
    at configFromInput (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:2547:9)
    at prepareConfig (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:2530:9)
    at createFromConfig (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:2497:40)
    at createLocalOrUTC (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:2584:12)
    at createLocal (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:2588:12)
    at hooks (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\moment\moment.js:16:25)
    at typeValue (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\node-wmi\lib\Query.js:208:15)
    at extractProperty (D:\Users\VertigoRay\Git\desktop\PhoneHome\node_modules\node-wmi\lib\Query.js:232:13)
[ { BuildNumber: undefined,
    Caption: '0601',
    CodeSet: undefined,
    ...
```

**Comment by s-a** [comment]
It seems new version was not published to NPM. 😮

**Comment by VertigoRay** [comment]
Is it just because a new release hasn't been made? Need this and #6 to be published to NPM.

CC: @jgrusling @jpgrusling
